# Generated by Django 2.0 on 2022-05-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete='CASCADE', related_name='children', to='hadith.Hadith')),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
