# Generated by Django 2.0 on 2022-05-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0003_auto_20220521_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hadith',
            old_name='description',
            new_name='description_arb',
        ),
        migrations.AddField(
            model_name='hadith',
            name='description_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hadith',
            name='description_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hadith',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
